version: '3.7'
services:
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    image: waves_client
    container_name: waves_client_container
    command: npm start
    volumes:
      - ./client/:/usr/src/waves2020/client/
      - /usr/src/waves2020/client/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - waves_network
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: waves_server
    container_name: waves_server_container
    restart: always
    command: npm run server
    volumes:
      - ./server/:/usr/src/waves2020/server/
      - /usr/src/waves2020/server/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/testNames
      - CHOKIDAR_USEPOLLING=true
    networks:
      - waves_network 
  mongo:
    image: mongo
    restart: always
    container_name: waves_mongo_container
    ports:
      - '27017:27017'
    networks:
      - waves_network
    volumes:
      - /data/db

networks:
  waves_network:
      driver: bridge
    
volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local